class ISO3166:
    dictionary = [
        {"country name": "Afghanistan", "alpha2": "AF", "alpha3": "AFG", "numeric": "4"},
        {"country name": "Åland Islands", "alpha2": "AX", "alpha3": "ALA", "numeric": "248"},
        {"country name": "Albania", "alpha2": "AL", "alpha3": "ALB", "numeric": "8"},
        {"country name": "Algeria", "alpha2": "DZ", "alpha3": "DZA", "numeric": "12"},
        {"country name": "American Samoa", "alpha2": "AS", "alpha3": "ASM", "numeric": "16"},
        {"country name": "Andorra", "alpha2": "AD", "alpha3": "AND", "numeric": "20"},
        {"country name": "Angola", "alpha2": "AO", "alpha3": "AGO", "numeric": "24"},
        {"country name": "Anguilla", "alpha2": "AI", "alpha3": "AIA", "numeric": "660"},
        {"country name": "Antarctica", "alpha2": "AQ", "alpha3": "ATA", "numeric": "10"},
        {"country name": "Antigua and Barbuda", "alpha2": "AG", "alpha3": "ATG", "numeric": "28"},
        {"country name": "Argentina", "alpha2": "AR", "alpha3": "ARG", "numeric": "32"},
        {"country name": "Armenia", "alpha2": "AM", "alpha3": "ARM", "numeric": "51"},
        {"country name": "Aruba", "alpha2": "AW", "alpha3": "ABW", "numeric": "533"},
        {"country name": "Australia", "alpha2": "AU", "alpha3": "AUS", "numeric": "36"},
        {"country name": "Austria", "alpha2": "AT", "alpha3": "AUT", "numeric": "40"},
        {"country name": "Azerbaijan", "alpha2": "AZ", "alpha3": "AZE", "numeric": "31"},
        {"country name": "Bahamas", "alpha2": "BS", "alpha3": "BHS", "numeric": "44"},
        {"country name": "Bahrain", "alpha2": "BH", "alpha3": "BHR", "numeric": "48"},
        {"country name": "Bangladesh", "alpha2": "BD", "alpha3": "BGD", "numeric": "50"},
        {"country name": "Barbados", "alpha2": "BB", "alpha3": "BRB", "numeric": "52"},
        {"country name": "Belarus", "alpha2": "BY", "alpha3": "BLR", "numeric": "112"},
        {"country name": "Belgium", "alpha2": "BE", "alpha3": "BEL", "numeric": "56"},
        {"country name": "Belize", "alpha2": "BZ", "alpha3": "BLZ", "numeric": "84"},
        {"country name": "Benin", "alpha2": "BJ", "alpha3": "BEN", "numeric": "204"},
        {"country name": "Bermuda", "alpha2": "BM", "alpha3": "BMU", "numeric": "60"},
        {"country name": "Bhutan", "alpha2": "BT", "alpha3": "BTN", "numeric": "64"},
        {"country name": "Bolivia (Plurinational State of)", "alpha2": "BO", "alpha3": "BOL", "numeric": "68"},
        {"country name": "Bonaire", "alpha2": "BQ", "alpha3": "BES", "numeric": "535"},
        {"country name": "Bosnia and Herzegovina", "alpha2": "BA", "alpha3": "BIH", "numeric": "70"},
        {"country name": "Botswana", "alpha2": "BW", "alpha3": "BWA", "numeric": "72"},
        {"country name": "Bouvet Island", "alpha2": "BV", "alpha3": "BVT", "numeric": "74"},
        {"country name": "Brazil", "alpha2": "BR", "alpha3": "BRA", "numeric": "76"},
        {"country name": "British Indian Ocean Territory", "alpha2": "IO", "alpha3": "IOT", "numeric": "86"},
        {"country name": "Brunei Darussalam", "alpha2": "BN", "alpha3": "BRN", "numeric": "96"},
        {"country name": "Bulgaria", "alpha2": "BG", "alpha3": "BGR", "numeric": "100"},
        {"country name": "Burkina Faso", "alpha2": "BF", "alpha3": "BFA", "numeric": "854"},
        {"country name": "Burundi", "alpha2": "BI", "alpha3": "BDI", "numeric": "108"},
        {"country name": "Cabo Verde", "alpha2": "CV", "alpha3": "CPV", "numeric": "132"},
        {"country name": "Cambodia", "alpha2": "KH", "alpha3": "KHM", "numeric": "116"},
        {"country name": "Cameroon", "alpha2": "CM", "alpha3": "CMR", "numeric": "120"},
        {"country name": "Canada", "alpha2": "CA", "alpha3": "CAN", "numeric": "124"},
        {"country name": "Cayman Islands", "alpha2": "KY", "alpha3": "CYM", "numeric": "136"},
        {"country name": "Central African Republic", "alpha2": "CF", "alpha3": "CAF", "numeric": "140"},
        {"country name": "Chad", "alpha2": "TD", "alpha3": "TCD", "numeric": "148"},
        {"country name": "Chile", "alpha2": "CL", "alpha3": "CHL", "numeric": "152"},
        {"country name": "China", "alpha2": "CN", "alpha3": "CHN", "numeric": "156"},
        {"country name": "Christmas Island", "alpha2": "CX", "alpha3": "CXR", "numeric": "162"},
        {"country name": "Cocos (Keeling) Islands", "alpha2": "CC", "alpha3": "CCK", "numeric": "166"},
        {"country name": "Colombia", "alpha2": "CO", "alpha3": "COL", "numeric": "170"},
        {"country name": "Comoros", "alpha2": "KM", "alpha3": "COM", "numeric": "174"},
        {"country name": "Democratic Republic Congo ", "alpha2": "CD", "alpha3": "COD", "numeric": "180"},
        {"country name": "Congo", "alpha2": "CG", "alpha3": "COG", "numeric": "178"},
        {"country name": "Cook Islands", "alpha2": "CK", "alpha3": "COK", "numeric": "184"},
        {"country name": "Costa Rica", "alpha2": "CR", "alpha3": "CRI", "numeric": "188"},
        {"country name": "Côte d'Ivoire", "alpha2": "CI", "alpha3": "CIV", "numeric": "384"},
        {"country name": "Croatia", "alpha2": "HR", "alpha3": "HRV", "numeric": "191"},
        {"country name": "Cuba", "alpha2": "CU", "alpha3": "CUB", "numeric": "192"},
        {"country name": "Curaçao", "alpha2": "CW", "alpha3": "CUW", "numeric": "531"},
        {"country name": "Cyprus", "alpha2": "CY", "alpha3": "CYP", "numeric": "196"},
        {"country name": "Czechia", "alpha2": "CZ", "alpha3": "CZE", "numeric": "203"},
        {"country name": "Denmark", "alpha2": "DK", "alpha3": "DNK", "numeric": "208"},
        {"country name": "Djibouti", "alpha2": "DJ", "alpha3": "DJI", "numeric": "262"},
        {"country name": "Dominica", "alpha2": "DM", "alpha3": "DMA", "numeric": "212"},
        {"country name": "Dominican Republic", "alpha2": "DO", "alpha3": "DOM", "numeric": "214"},
        {"country name": "Ecuador", "alpha2": "EC", "alpha3": "ECU", "numeric": "218"},
        {"country name": "Egypt", "alpha2": "EG", "alpha3": "EGY", "numeric": "818"},
        {"country name": "El Salvador", "alpha2": "SV", "alpha3": "SLV", "numeric": "222"},
        {"country name": "Equatorial Guinea", "alpha2": "GQ", "alpha3": "GNQ", "numeric": "226"},
        {"country name": "Eritrea", "alpha2": "ER", "alpha3": "ERI", "numeric": "232"},
        {"country name": "Estonia", "alpha2": "EE", "alpha3": "EST", "numeric": "233"},
        {"country name": "Eswatini", "alpha2": "SZ", "alpha3": "SWZ", "numeric": "748"},
        {"country name": "Ethiopia", "alpha2": "ET", "alpha3": "ETH", "numeric": "231"},
        {"country name": "Falkland Islands", "alpha2": "FK", "alpha3": "FLK", "numeric": "238"},
        {"country name": "Faroe Islands", "alpha2": "FO", "alpha3": "FRO", "numeric": "234"},
        {"country name": "Fiji", "alpha2": "FJ", "alpha3": "FJI", "numeric": "242"},
        {"country name": "Finland", "alpha2": "FI", "alpha3": "FIN", "numeric": "246"},
        {"country name": "France", "alpha2": "FR", "alpha3": "FRA", "numeric": "250"},
        {"country name": "French Guiana", "alpha2": "GF", "alpha3": "GUF", "numeric": "254"},
        {"country name": "French Polynesia", "alpha2": "PF", "alpha3": "PYF", "numeric": "258"},
        {"country name": "French Southern Territories", "alpha2": "TF", "alpha3": "ATF", "numeric": "260"},
        {"country name": "Gabon", "alpha2": "GA", "alpha3": "GAB", "numeric": "266"},
        {"country name": "Gambia", "alpha2": "GM", "alpha3": "GMB", "numeric": "270"},
        {"country name": "Georgia", "alpha2": "GE", "alpha3": "GEO", "numeric": "268"},
        {"country name": "Germany", "alpha2": "DE", "alpha3": "DEU", "numeric": "276"},
        {"country name": "Ghana", "alpha2": "GH", "alpha3": "GHA", "numeric": "288"},
        {"country name": "Gibraltar", "alpha2": "GI", "alpha3": "GIB", "numeric": "292"},
        {"country name": "Greece", "alpha2": "GR", "alpha3": "GRC", "numeric": "300"},
        {"country name": "Greenland", "alpha2": "GL", "alpha3": "GRL", "numeric": "304"},
        {"country name": "Grenada", "alpha2": "GD", "alpha3": "GRD", "numeric": "308"},
        {"country name": "Guadeloupe", "alpha2": "GP", "alpha3": "GLP", "numeric": "312"},
        {"country name": "Guam", "alpha2": "GU", "alpha3": "GUM", "numeric": "316"},
        {"country name": "Guatemala", "alpha2": "GT", "alpha3": "GTM", "numeric": "320"},
        {"country name": "Guernsey", "alpha2": "GG", "alpha3": "GGY", "numeric": "831"},
        {"country name": "Guinea", "alpha2": "GN", "alpha3": "GIN", "numeric": "324"},
        {"country name": "Guinea-Bissau", "alpha2": "GW", "alpha3": "GNB", "numeric": "624"},
        {"country name": "Guyana", "alpha2": "GY", "alpha3": "GUY", "numeric": "328"},
        {"country name": "Haiti", "alpha2": "HT", "alpha3": "HTI", "numeric": "332"},
        {"country name": "Heard Island and McDonald Islands", "alpha2": "HM", "alpha3": "HMD", "numeric": "334"},
        {"country name": "Holy ", "alpha2": "VA", "alpha3": "VAT", "numeric": "336"},
        {"country name": "Honduras", "alpha2": "HN", "alpha3": "HND", "numeric": "340"},
        {"country name": "Hong Kong", "alpha2": "HK", "alpha3": "HKG", "numeric": "344"},
        {"country name": "Hungary", "alpha2": "HU", "alpha3": "HUN", "numeric": "348"},
        {"country name": "Iceland", "alpha2": "IS", "alpha3": "ISL", "numeric": "352"},
        {"country name": "India", "alpha2": "IN", "alpha3": "IND", "numeric": "356"},
        {"country name": "Indonesia", "alpha2": "ID", "alpha3": "IDN", "numeric": "360"},
        {"country name": "Iran (Islamic Republic of)", "alpha2": "IR", "alpha3": "IRN", "numeric": "364"},
        {"country name": "Iraq", "alpha2": "IQ", "alpha3": "IRQ", "numeric": "368"},
        {"country name": "Ireland", "alpha2": "IE", "alpha3": "IRL", "numeric": "372"},
        {"country name": "Isle of Man", "alpha2": "IM", "alpha3": "IMN", "numeric": "833"},
        {"country name": "Israel", "alpha2": "IL", "alpha3": "ISR", "numeric": "376"},
        {"country name": "Italy", "alpha2": "IT", "alpha3": "ITA", "numeric": "380"},
        {"country name": "Jamaica", "alpha2": "JM", "alpha3": "JAM", "numeric": "388"},
        {"country name": "Japan", "alpha2": "JP", "alpha3": "JPN", "numeric": "392"},
        {"country name": "Jersey", "alpha2": "JE", "alpha3": "JEY", "numeric": "832"},
        {"country name": "Jordan", "alpha2": "JO", "alpha3": "JOR", "numeric": "400"},
        {"country name": "Kazakhstan", "alpha2": "KZ", "alpha3": "KAZ", "numeric": "398"},
        {"country name": "Kenya", "alpha2": "KE", "alpha3": "KEN", "numeric": "404"},
        {"country name": "Kiribati", "alpha2": "KI", "alpha3": "KIR", "numeric": "296"},
        {"country name": "Korea (the Democratic People's Republic of)", "alpha2": "KP", "alpha3": "PRK",
         "numeric": "408"},
        {"country name": "Korea (the Republic of)", "alpha2": "KR", "alpha3": "KOR", "numeric": "410"},
        {"country name": "Kuwait", "alpha2": "KW", "alpha3": "KWT", "numeric": "414"},
        {"country name": "Kyrgyzstan", "alpha2": "KG", "alpha3": "KGZ", "numeric": "417"},
        {"country name": "Lao People's Democratic Republic", "alpha2": "LA", "alpha3": "LAO", "numeric": "418"},
        {"country name": "Latvia", "alpha2": "LV", "alpha3": "LVA", "numeric": "428"},
        {"country name": "Lebanon", "alpha2": "LB", "alpha3": "LBN", "numeric": "422"},
        {"country name": "Lesotho", "alpha2": "LS", "alpha3": "LSO", "numeric": "426"},
        {"country name": "Liberia", "alpha2": "LR", "alpha3": "LBR", "numeric": "430"},
        {"country name": "Libya", "alpha2": "LY", "alpha3": "LBY", "numeric": "434"},
        {"country name": "Liechtenstein", "alpha2": "LI", "alpha3": "LIE", "numeric": "438"},
        {"country name": "Lithuania", "alpha2": "LT", "alpha3": "LTU", "numeric": "440"},
        {"country name": "Luxembourg", "alpha2": "LU", "alpha3": "LUX", "numeric": "442"},
        {"country name": "Macao", "alpha2": "MO", "alpha3": "MAC", "numeric": "446"},
        {"country name": "North Macedonia", "alpha2": "MK", "alpha3": "MKD", "numeric": "807"},
        {"country name": "Madagascar", "alpha2": "MG", "alpha3": "MDG", "numeric": "450"},
        {"country name": "Malawi", "alpha2": "MW", "alpha3": "MWI", "numeric": "454"},
        {"country name": "Malaysia", "alpha2": "MY", "alpha3": "MYS", "numeric": "458"},
        {"country name": "Maldives", "alpha2": "MV", "alpha3": "MDV", "numeric": "462"},
        {"country name": "Mali", "alpha2": "ML", "alpha3": "MLI", "numeric": "466"},
        {"country name": "Malta", "alpha2": "MT", "alpha3": "MLT", "numeric": "470"},
        {"country name": "Marshall Islands", "alpha2": "MH", "alpha3": "MHL", "numeric": "584"},
        {"country name": "Martinique", "alpha2": "MQ", "alpha3": "MTQ", "numeric": "474"},
        {"country name": "Mauritania", "alpha2": "MR", "alpha3": "MRT", "numeric": "478"},
        {"country name": "Mauritius", "alpha2": "MU", "alpha3": "MUS", "numeric": "480"},
        {"country name": "Mayotte", "alpha2": "YT", "alpha3": "MYT", "numeric": "175"},
        {"country name": "Mexico", "alpha2": "MX", "alpha3": "MEX", "numeric": "484"},
        {"country name": "Micronesia (Federated States of)", "alpha2": "FM", "alpha3": "FSM", "numeric": "583"},
        {"country name": "Moldova (the Republic of)", "alpha2": "MD", "alpha3": "MDA", "numeric": "498"},
        {"country name": "Monaco", "alpha2": "MC", "alpha3": "MCO", "numeric": "492"},
        {"country name": "Mongolia", "alpha2": "MN", "alpha3": "MNG", "numeric": "496"},
        {"country name": "Montenegro", "alpha2": "ME", "alpha3": "MNE", "numeric": "499"},
        {"country name": "Montserrat", "alpha2": "MS", "alpha3": "MSR", "numeric": "500"},
        {"country name": "Morocco", "alpha2": "MA", "alpha3": "MAR", "numeric": "504"},
        {"country name": "Mozambique", "alpha2": "MZ", "alpha3": "MOZ", "numeric": "508"},
        {"country name": "Myanmar", "alpha2": "MM", "alpha3": "MMR", "numeric": "104"},
        {"country name": "Namibia", "alpha2": "NA", "alpha3": "NAM", "numeric": "516"},
        {"country name": "Nauru", "alpha2": "NR", "alpha3": "NRU", "numeric": "520"},
        {"country name": "Nepal", "alpha2": "NP", "alpha3": "NPL", "numeric": "524"},
        {"country name": "Netherlands", "alpha2": "NL", "alpha3": "NLD", "numeric": "528"},
        {"country name": "New Caledonia", "alpha2": "NC", "alpha3": "NCL", "numeric": "540"},
        {"country name": "New Zealand", "alpha2": "NZ", "alpha3": "NZL", "numeric": "554"},
        {"country name": "Nicaragua", "alpha2": "NI", "alpha3": "NIC", "numeric": "558"},
        {"country name": "Niger", "alpha2": "NE", "alpha3": "NER", "numeric": "562"},
        {"country name": "Nigeria", "alpha2": "NG", "alpha3": "NGA", "numeric": "566"},
        {"country name": "Niue", "alpha2": "NU", "alpha3": "NIU", "numeric": "570"},
        {"country name": "Norfolk Island", "alpha2": "NF", "alpha3": "NFK", "numeric": "574"}
    ]

    @staticmethod
    def find_country_by_numeric_code(numStr=""):
        numStr = numStr.lstrip("0")
        for x in ISO3166.dictionary:
            if x["numeric"] == numStr:
                return x
        return {"country name": None, "alpha2": None, "alpha3": None, "numeric": numStr}

    @staticmethod
    def find_country_by_alpha2(alpha2=""):
        for x in ISO3166.dictionary:
            if x["alpha2"] == alpha2:
                return x
        return {"country name": None, "alpha2": alpha2, "alpha3": None, "numeric": None}

    @staticmethod
    def find_country_by_alpha3(alpha3=""):
        for x in ISO3166.dictionary:
            if x["alpha3"] == alpha3:
                return x
        return {"country name": None, "alpha2": None, "alpha3": alpha3, "numeric": None}
