class ISO4217:
    dictionary = [
        {"code": "AED", "num": "784", "exponent": "2", "currency": "United Arab Emirates dirham"},
        {"code": "AFN", "num": "971", "exponent": "2", "currency": "Afghan afghani"},
        {"code": "ALL", "num": "8", "exponent": "2", "currency": "Albanian lek"},
        {"code": "AMD", "num": "51", "exponent": "2", "currency": "Armenian dram"},
        {"code": "ANG", "num": "532", "exponent": "2", "currency": "Netherlands Antillean guilder"},
        {"code": "AOA", "num": "973", "exponent": "2", "currency": "Angolan kwanza"},
        {"code": "ARS", "num": "32", "exponent": "2", "currency": "Argentine peso"},
        {"code": "AUD", "num": "36", "exponent": "2", "currency": "Australian dollar"},
        {"code": "AWG", "num": "533", "exponent": "2", "currency": "Aruban florin"},
        {"code": "AZN", "num": "944", "exponent": "2", "currency": "Azerbaijani manat"},
        {"code": "BAM", "num": "977", "exponent": "2", "currency": "Bosnia and Herzegovina convertible mark"},
        {"code": "BBD", "num": "52", "exponent": "2", "currency": "Barbados dollar"},
        {"code": "BDT", "num": "50", "exponent": "2", "currency": "Bangladeshi taka"},
        {"code": "BGN", "num": "975", "exponent": "2", "currency": "Bulgarian lev"},
        {"code": "BHD", "num": "48", "exponent": "3", "currency": "Bahraini dinar"},
        {"code": "BIF", "num": "108", "exponent": "0", "currency": "Burundian franc"},
        {"code": "BMD", "num": "60", "exponent": "2", "currency": "Bermudian dollar"},
        {"code": "BND", "num": "96", "exponent": "2", "currency": "Brunei dollar"},
        {"code": "BOB", "num": "68", "exponent": "2", "currency": "Boliviano"},
        {"code": "BOV", "num": "984", "exponent": "2", "currency": "Bolivian Mvdol (funds code)"},
        {"code": "BRL", "num": "986", "exponent": "2", "currency": "Brazilian real"},
        {"code": "BSD", "num": "44", "exponent": "2", "currency": "Bahamian dollar"},
        {"code": "BTN", "num": "64", "exponent": "2", "currency": "Bhutanese ngultrum"},
        {"code": "BWP", "num": "72", "exponent": "2", "currency": "Botswana pula"},
        {"code": "BYN", "num": "933", "exponent": "2", "currency": "Belarusian ruble"},
        {"code": "BZD", "num": "84", "exponent": "2", "currency": "Belize dollar"},
        {"code": "CAD", "num": "124", "exponent": "2", "currency": "Canadian dollar"},
        {"code": "CDF", "num": "976", "exponent": "2", "currency": "Congolese franc"},
        {"code": "CHE", "num": "947", "exponent": "2", "currency": "WIR euro (complementary currency)"},
        {"code": "CHF", "num": "756", "exponent": "2", "currency": "Swiss franc"},
        {"code": "CHW", "num": "948", "exponent": "2", "currency": "WIR franc (complementary currency)"},
        {"code": "CLF", "num": "990", "exponent": "4", "currency": "Unidad de Fomento (funds code)"},
        {"code": "CLP", "num": "152", "exponent": "0", "currency": "Chilean peso"},
        {"code": "CNY", "num": "156", "exponent": "2", "currency": "Chinese yuan"},
        {"code": "COP", "num": "170", "exponent": "2", "currency": "Colombian peso"},
        {"code": "COU", "num": "970", "exponent": "2", "currency": "Unidad de Valor Real (UVR) (funds code)"},
        {"code": "CRC", "num": "188", "exponent": "2", "currency": "Costa Rican colon"},
        {"code": "CUC", "num": "931", "exponent": "2", "currency": "Cuban convertible peso"},
        {"code": "CUP", "num": "192", "exponent": "2", "currency": "Cuban peso"},
        {"code": "CVE", "num": "132", "exponent": "2", "currency": "Cape Verdean escudo"},
        {"code": "CZK", "num": "203", "exponent": "2", "currency": "Czech koruna"},
        {"code": "DJF", "num": "262", "exponent": "0", "currency": "Djiboutian franc"},
        {"code": "DKK", "num": "208", "exponent": "2", "currency": "Danish krone"},
        {"code": "DOP", "num": "214", "exponent": "2", "currency": "Dominican peso"},
        {"code": "DZD", "num": "12", "exponent": "2", "currency": "Algerian dinar"},
        {"code": "EGP", "num": "818", "exponent": "2", "currency": "Egyptian pound"},
        {"code": "ERN", "num": "232", "exponent": "2", "currency": "Eritrean nakfa"},
        {"code": "ETB", "num": "230", "exponent": "2", "currency": "Ethiopian birr"},
        {"code": "EUR", "num": "978", "exponent": "2", "currency": "Euro"},
        {"code": "FJD", "num": "242", "exponent": "2", "currency": "Fiji dollar"},
        {"code": "FKP", "num": "238", "exponent": "2", "currency": "Falkland Islands pound"},
        {"code": "GBP", "num": "826", "exponent": "2", "currency": "Pound sterling"},
        {"code": "GEL", "num": "981", "exponent": "2", "currency": "Georgian lari"},
        {"code": "GHS", "num": "936", "exponent": "2", "currency": "Ghanaian cedi"},
        {"code": "GIP", "num": "292", "exponent": "2", "currency": "Gibraltar pound"},
        {"code": "GMD", "num": "270", "exponent": "2", "currency": "Gambian dalasi"},
        {"code": "GNF", "num": "324", "exponent": "0", "currency": "Guinean franc"},
        {"code": "GTQ", "num": "320", "exponent": "2", "currency": "Guatemalan quetzal"},
        {"code": "GYD", "num": "328", "exponent": "2", "currency": "Guyanese dollar"},
        {"code": "HKD", "num": "344", "exponent": "2", "currency": "Hong Kong dollar"},
        {"code": "HNL", "num": "340", "exponent": "2", "currency": "Honduran lempira"},
        {"code": "HRK", "num": "191", "exponent": "2", "currency": "Croatian kuna"},
        {"code": "HTG", "num": "332", "exponent": "2", "currency": "Haitian gourde"},
        {"code": "HUF", "num": "348", "exponent": "2", "currency": "Hungarian forint"},
        {"code": "IDR", "num": "360", "exponent": "2", "currency": "Indonesian rupiah"},
        {"code": "ILS", "num": "376", "exponent": "2", "currency": "Israeli new shekel"},
        {"code": "INR", "num": "356", "exponent": "2", "currency": "Indian rupee"},
        {"code": "IQD", "num": "368", "exponent": "3", "currency": "Iraqi dinar"},
        {"code": "IRR", "num": "364", "exponent": "2", "currency": "Iranian rial"},
        {"code": "ISK", "num": "352", "exponent": "0", "currency": "Icelandic króna"},
        {"code": "JMD", "num": "388", "exponent": "2", "currency": "Jamaican dollar"},
        {"code": "JOD", "num": "400", "exponent": "3", "currency": "Jordanian dinar"},
        {"code": "JPY", "num": "392", "exponent": "0", "currency": "Japanese yen"},
        {"code": "KES", "num": "404", "exponent": "2", "currency": "Kenyan shilling"},
        {"code": "KGS", "num": "417", "exponent": "2", "currency": "Kyrgyzstani som"},
        {"code": "KHR", "num": "116", "exponent": "2", "currency": "Cambodian riel"},
        {"code": "KMF", "num": "174", "exponent": "0", "currency": "Comoro franc"},
        {"code": "KPW", "num": "408", "exponent": "2", "currency": "North Korean won"},
        {"code": "KRW", "num": "410", "exponent": "0", "currency": "South Korean won"},
        {"code": "KWD", "num": "414", "exponent": "3", "currency": "Kuwaiti dinar"},
        {"code": "KYD", "num": "136", "exponent": "2", "currency": "Cayman Islands dollar"},
        {"code": "KZT", "num": "398", "exponent": "2", "currency": "Kazakhstani tenge"},
        {"code": "LAK", "num": "418", "exponent": "2", "currency": "Lao kip"},
        {"code": "LBP", "num": "422", "exponent": "2", "currency": "Lebanese pound"},
        {"code": "LKR", "num": "144", "exponent": "2", "currency": "Sri Lankan rupee"},
        {"code": "LRD", "num": "430", "exponent": "2", "currency": "Liberian dollar"},
        {"code": "LSL", "num": "426", "exponent": "2", "currency": "Lesotho loti"},
        {"code": "LYD", "num": "434", "exponent": "3", "currency": "Libyan dinar"},
        {"code": "MAD", "num": "504", "exponent": "2", "currency": "Moroccan dirham"},
        {"code": "MDL", "num": "498", "exponent": "2", "currency": "Moldovan leu"},
        {"code": "MGA", "num": "969", "exponent": "2", "currency": "Malagasy ariary"},
        {"code": "MKD", "num": "807", "exponent": "2", "currency": "Macedonian denar"},
        {"code": "MMK", "num": "104", "exponent": "2", "currency": "Myanmar kyat"},
        {"code": "MNT", "num": "496", "exponent": "2", "currency": "Mongolian tögrög"},
        {"code": "MOP", "num": "446", "exponent": "2", "currency": "Macanese pataca"},
        {"code": "MRU", "num": "929", "exponent": "2", "currency": "Mauritanian ouguiya"},
        {"code": "MUR", "num": "480", "exponent": "2", "currency": "Mauritian rupee"},
        {"code": "MVR", "num": "462", "exponent": "2", "currency": "Maldivian rufiyaa"},
        {"code": "MWK", "num": "454", "exponent": "2", "currency": "Malawian kwacha"},
        {"code": "MXN", "num": "484", "exponent": "2", "currency": "Mexican peso"},
        {"code": "MXV", "num": "979", "exponent": "2", "currency": "Mexican Unidad de Inversion (UDI) (funds code)"},
        {"code": "MYR", "num": "458", "exponent": "2", "currency": "Malaysian ringgit"},
        {"code": "MZN", "num": "943", "exponent": "2", "currency": "Mozambican metical"},
        {"code": "NAD", "num": "516", "exponent": "2", "currency": "Namibian dollar"},
        {"code": "NGN", "num": "566", "exponent": "2", "currency": "Nigerian naira"},
        {"code": "NIO", "num": "558", "exponent": "2", "currency": "Nicaraguan córdoba"},
        {"code": "NOK", "num": "578", "exponent": "2", "currency": "Norwegian krone"},
        {"code": "NPR", "num": "524", "exponent": "2", "currency": "Nepalese rupee"},
        {"code": "NZD", "num": "554", "exponent": "2", "currency": "New Zealand dollar"},
        {"code": "OMR", "num": "512", "exponent": "3", "currency": "Omani rial"},
        {"code": "PAB", "num": "590", "exponent": "2", "currency": "Panamanian balboa"},
        {"code": "PEN", "num": "604", "exponent": "2", "currency": "Peruvian sol"},
        {"code": "PGK", "num": "598", "exponent": "2", "currency": "Papua New Guinean kina"},
        {"code": "PHP", "num": "608", "exponent": "2", "currency": "Philippine peso"},
        {"code": "PKR", "num": "586", "exponent": "2", "currency": "Pakistani rupee"},
        {"code": "PLN", "num": "985", "exponent": "2", "currency": "Polish złoty"},
        {"code": "PYG", "num": "600", "exponent": "0", "currency": "Paraguayan guaraní"},
        {"code": "QAR", "num": "634", "exponent": "2", "currency": "Qatari riyal"},
        {"code": "RON", "num": "946", "exponent": "2", "currency": "Romanian leu"},
        {"code": "RSD", "num": "941", "exponent": "2", "currency": "Serbian dinar"},
        {"code": "RUB", "num": "643", "exponent": "2", "currency": "Russian ruble"},
        {"code": "RWF", "num": "646", "exponent": "0", "currency": "Rwandan franc"},
        {"code": "SAR", "num": "682", "exponent": "2", "currency": "Saudi riyal"},
        {"code": "SBD", "num": "90", "exponent": "2", "currency": "Solomon Islands dollar"},
        {"code": "SCR", "num": "690", "exponent": "2", "currency": "Seychelles rupee"},
        {"code": "SDG", "num": "938", "exponent": "2", "currency": "Sudanese pound"},
        {"code": "SEK", "num": "752", "exponent": "2", "currency": "Swedish krona/kronor"},
        {"code": "SGD", "num": "702", "exponent": "2", "currency": "Singapore dollar"},
        {"code": "SHP", "num": "654", "exponent": "2", "currency": "Saint Helena pound"},
        {"code": "SLL", "num": "694", "exponent": "2", "currency": "Sierra Leonean leone"},
        {"code": "SOS", "num": "706", "exponent": "2", "currency": "Somali shilling"},
        {"code": "SRD", "num": "968", "exponent": "2", "currency": "Surinamese dollar"},
        {"code": "SSP", "num": "728", "exponent": "2", "currency": "South Sudanese pound"},
        {"code": "STN", "num": "930", "exponent": "2", "currency": "São Tomé and Príncipe dobra"},
        {"code": "SVC", "num": "222", "exponent": "2", "currency": "Salvadoran colón"},
        {"code": "SYP", "num": "760", "exponent": "2", "currency": "Syrian pound"},
        {"code": "SZL", "num": "748", "exponent": "2", "currency": "Swazi lilangeni"},
        {"code": "THB", "num": "764", "exponent": "2", "currency": "Thai baht"},
        {"code": "TJS", "num": "972", "exponent": "2", "currency": "Tajikistani somoni"},
        {"code": "TMT", "num": "934", "exponent": "2", "currency": "Turkmenistan manat"},
        {"code": "TND", "num": "788", "exponent": "3", "currency": "Tunisian dinar"},
        {"code": "TOP", "num": "776", "exponent": "2", "currency": "Tongan paʻanga"},
        {"code": "TRY", "num": "949", "exponent": "2", "currency": "Turkish lira"},
        {"code": "TTD", "num": "780", "exponent": "2", "currency": "Trinidad and Tobago dollar"},
        {"code": "TWD", "num": "901", "exponent": "2", "currency": "New Taiwan dollar"},
        {"code": "TZS", "num": "834", "exponent": "2", "currency": "Tanzanian shilling"},
        {"code": "UAH", "num": "980", "exponent": "2", "currency": "Ukrainian hryvnia"},
        {"code": "UGX", "num": "800", "exponent": "0", "currency": "Ugandan shilling"},
        {"code": "USD", "num": "840", "exponent": "2", "currency": "United States dollar"},
        {"code": "USN", "num": "997", "exponent": "2", "currency": "United States dollar (next day) (funds code)"},
        {"code": "UYI", "num": "940", "exponent": "0",
         "currency": "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"},
        {"code": "UYU", "num": "858", "exponent": "2", "currency": "Uruguayan peso"},
        {"code": "UYW", "num": "927", "exponent": "4", "currency": "Unidad previsional"},
        {"code": "UZS", "num": "860", "exponent": "2", "currency": "Uzbekistan som"},
        {"code": "VES", "num": "928", "exponent": "2", "currency": "Venezuelan bolívar soberano"},
        {"code": "VND", "num": "704", "exponent": "0", "currency": "Vietnamese đồng"},
        {"code": "VUV", "num": "548", "exponent": "0", "currency": "Vanuatu vatu"},
        {"code": "WST", "num": "882", "exponent": "2", "currency": "Samoan tala"},
        {"code": "XAF", "num": "950", "exponent": "0", "currency": "CFA franc BEAC"},
        {"code": "XAG", "num": "961", "exponent": "0", "currency": "Silver (one troy ounce)"},
        {"code": "XAU", "num": "959", "exponent": "0", "currency": "Gold (one troy ounce)"},
        {"code": "XBA", "num": "955", "exponent": "0",
         "currency": "European Composite Unit (EURCO) (bond market unit)"},
        {"code": "XBB", "num": "956", "exponent": "0",
         "currency": "European Monetary Unit (E.M.U.-6) (bond market unit)"},
        {"code": "XBC", "num": "957", "exponent": "0",
         "currency": "European Unit of Account 9 (E.U.A.-9) (bond market unit)"},
        {"code": "XBD", "num": "958", "exponent": "0",
         "currency": "European Unit of Account 17 (E.U.A.-17) (bond market unit)"},
        {"code": "XCD", "num": "951", "exponent": "2", "currency": "East Caribbean dollar"},
        {"code": "XDR", "num": "960", "exponent": "0", "currency": "Special drawing rights"},
        {"code": "XOF", "num": "952", "exponent": "0", "currency": "CFA franc BCEAO"},
        {"code": "XPD", "num": "964", "exponent": "0", "currency": "Palladium (one troy ounce)"},
        {"code": "XPF", "num": "953", "exponent": "0", "currency": "CFP franc (franc Pacifique)"},
        {"code": "XPT", "num": "962", "exponent": "0", "currency": "Platinum (one troy ounce)"},
        {"code": "XSU", "num": "994", "exponent": "0", "currency": "SUCRE"},
        {"code": "XTS", "num": "963", "exponent": "0", "currency": "Code reserved for testing"},
        {"code": "XUA", "num": "965", "exponent": "0", "currency": "ADB Unit of Account"},
        {"code": "XXX", "num": "999", "exponent": "0", "currency": "No currency "},
        {"code": "YER", "num": "886", "exponent": "2", "currency": "Yemeni rial"},
        {"code": "ZAR", "num": "710", "exponent": "2", "currency": "South African rand"},
        {"code": "ZMW", "num": "967", "exponent": "2", "currency": "Zambian kwacha"},
        {"code": "ZWL", "num": "932", "exponent": "2", "currency": "Zimbabwean dollar"}
    ]

    @staticmethod
    def find_currency_code(numStr=""):
        numStr = numStr.lstrip("0")
        for x in ISO4217.dictionary:
            if x["num"] == numStr:
                return x
        return {"code": "XXX", "num": numStr, "exponent": "0", "currency": "No currency "}
